runtime: python27
threadsafe: true
api_version: 1
service: quiz
manual_scaling:
  instances: 1
# 利用者規模に応じて変更する必要あり
# 次から選択: B1, B2, B4, B4_1G, and B8
instance_class: B1

#[START_EXCLUDE]
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?setuptools/script \(dev\).tmpl$
#[END_EXCLUDE]

handlers:
- url: /static
  static_dir: static
  secure: always
#  login: admin
- url: .*
  script: main.app
